### ISSUE TITLE
Hardware Monitor applet forgets font size and fails to update after reboot.

### ISSUE THREAD

**Issue by ShapeShifter499** [OmegaPhil/hardware-monitor-applet#6] opened 2014-07-23 18:27 UTC
Hi,

I'm using this in ArchLinux XFCE4 and I'm noticing that after reboots any text will be enlarged to pt10 when I originally set pt8. Also instances of "Hardware Monitor" that are set to keep track of network data speed fail to update after reboots. I can reset this but doing that EVERY single reboot is getting annoying. I installed this through the AUR package https://aur.archlinux.org/packages/xfce4-hardware-monitor-applet-git/  But since it grabs from your git I'm assuming it's an issue with your code and not the package in the AUR.

**Comment by OmegaPhil** [comment] 2014-07-23 18:48
Evening, congrats on being the first external person to post a bug! Please can you post the plugin's configuration file or files for multiple instances, it should be '~/.config/xfce4/panel/hardware-monitor-*.rc'.

I use one instance with two network bandwidth monitors in a graph - never screws up here (been using this code for months now), but then I don't use the text output.

**Comment by ShapeShifter499** [comment] 2014-07-23 20:25
Here is those files all in one paste https://pastee.org/fsyf9     LOL I notice that I am the first and only other one so far posting bug reports.

**Comment by OmegaPhil** [comment] 2014-07-23 20:30
Cool, you use a fair few. I'll look into this tomorrow, with any luck it'll be a simple change as it won't have been properly tested (I merely ported the applet then fiddled a bit with the graph output).

**Comment by OmegaPhil** [comment] 2014-07-24 16:32
I'm looking at this now - I can confirm the font size saving is junk - there is no saving at all, and it looks like there never was! I will implement this.

The network bandwidth problem I'm not sure about. I'll test on my laptop after sorting the font size out, but incase you get this first, the following commands kill the XFCE4 panel, enable debug output and start it up in the current terminal:

`xfce4-panel -q; sleep 2; PANEL_DEBUG=1 xfce4-panel &`

Are there any interesting complaints output? Does this only break after a reboot or restarting the plugin like above?

**Comment by OmegaPhil** [comment] 2014-07-24 18:16
Right, I was confused - the 'font name' is actually a collection of font details including the name, size, other style stuff etc, which was already being saved. I have found and fixed the screwup - whenever the preferences dialog was shown, the order of initialising the widgets meant that any customisation of the font was always overwritten.

**Comment by OmegaPhil** [comment] 2014-07-24 18:39
I have configured Hardware Monitor on my laptop with both a wired and wireless connection, worked, rebooted, still worked - so I'm not able to recreate your problem. The plugin uses libgtop to read the relevant sys files, e.g. '/sys/class/net/wlan0/statistics/rx_bytes', so you would think it would be simple enough to not break.

**Comment by ShapeShifter499** [comment] 2014-07-25 02:41
I no longer notice any bug on reboots after I configured XFCE with one panel. So maybe the bug only happens when there are multiple panels?

**Comment by OmegaPhil** [comment] 2014-07-25 07:07
Please can I have a screenshot of your desktop, I'll set up something similar on my laptop.

**Comment by ShapeShifter499** [comment] 2014-07-25 11:52
The setup I had before I changed it to a single panel was the default one you would get when you first use XFCE. Looks like this Google image I found http://www.searsportmaine.com/images/fedora-18-xfce-i6.png (not my screen shot)  The old setup suffered from the reboot bug but my new setup with one panel does not suffer from the bug and looks like http://i.imgur.com/JlcdlXM.png (my own screen shot)   I'm thinking maybe it's something to do with multiple panels.

**Comment by OmegaPhil** [comment] 2014-07-25 13:36
OK - the laptop has two panels but does not exhibit the bug. I think I need more users with this issue to continue then - other than that, I'm waiting for your response to https://github.com/OmegaPhil/hardware-monitor-applet/issues/6#issuecomment-50043131

**Comment by ShapeShifter499** [comment] 2014-07-25 16:34
I don't know what I did but I no longer experience the bug.

**Comment by OmegaPhil** [comment] 2014-07-25 16:36
Oh, not even multiple panels? OK, I will close this bug and release a new version!

**Closed as completed by OmegaPhil** 2014-07-25 16:36 UTC
Labels: bug
